//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTECAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Cliente()
        {
            this.TB_Endereco = new HashSet<TB_Endereco>();
        }
    
        public int IdCliente { get; set; }
        public string Nome { get; set; }
        public Nullable<int> IdPerfil { get; set; }
        public string Telefone { get; set; }
        public string Email { get; set; }
        public string CPF { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public System.DateTime DataNasc { get; set; }
        public string Sexo { get; set; }
        public Nullable<System.DateTime> UltimaAtualizacao { get; set; }
        public Nullable<bool> Removido { get; set; }
    
        public virtual TB_Perfil TB_Perfil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Endereco> TB_Endereco { get; set; }
    }
}
