//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTECAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Perfil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Perfil()
        {
            this.TB_Cliente = new HashSet<TB_Cliente>();
        }
    
        public int IdPerfil { get; set; }
        public string Nome { get; set; }
        public bool Removido { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Cliente> TB_Cliente { get; set; }
    }
}
